spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cors:
  allowed-origins: http://localhost:3000

logging:
  level:
    com.example.dada: DEBUG
