spring:
  application:
    name: dada
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dada}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:your-email@example.com}
    password: ${SPRING_MAIL_PASSWORD:change-me}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:change-me}
  expiration: ${JWT_EXPIRATION:86400000}

otp:
  expiration-minutes: ${OTP_EXPIRATION_MINUTES:5}
  length: ${OTP_LENGTH:6}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui.html

logging:
  level:
    org.springframework.security: INFO
    com.example.dada: DEBUG

whatsapp:
  api-base-url: ${WHATSAPP_API_BASE_URL:https://graph.facebook.com/v19.0}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID:}
  access-token: ${WHATSAPP_ACCESS_TOKEN:}
  verify-token: ${WHATSAPP_VERIFY_TOKEN:sample-verify-token}
  admin-notify-number: ${WHATSAPP_ADMIN_NUMBER:}
